#!/usr/bin/env python

import smtplib
import sys
import argparse
from email.mime.text import MIMEText

def process_args(parser):
    return parser.parse_args()

def main():
    parser = argparse.ArgumentParser(description='A basic python app to send email')

    parser.add_argument('--from', '-f', action="store", dest='sender', type=str, required=True)
    parser.add_argument('--to', '-t', nargs='+', action="store", dest='to', type=str, required=True)
    parser.add_argument('--subject', '-s', action="store", dest='subject', type=str, required=True)
    parser.add_argument('--body', '-b', action="store", dest='body', type=str, required=True)

    if len(sys.argv)==1:
        print parser.print_help()
        parser.exit(1)
        
    args = process_args(parser)

    smtp_server = '172.16.10.40'
    sender = args.sender
    receivers = args.to
    subject = args.subject
    body = args.body

    message = MIMEText(body)
    message['Subject'] = subject
    message['From'] = sender
    message['To'] = ", ".join(receivers)

    try:
        smtpObj = smtplib.SMTP(smtp_server)
        smtpObj.sendmail(sender, receivers, message.as_string())         
        print "Sent email successfully."
    except Exception as e:
        print "ERROR: unable to send email - ", e 

main()       
