# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qjobSpooler_UI.ui'
#
# Created: Sun Nov 23 20:12:25 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_qSpooler(object):
    def setupUi(self, qSpooler):
        qSpooler.setObjectName("qSpooler")
        qSpooler.setWindowModality(QtCore.Qt.NonModal)
        qSpooler.resize(708, 629)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        qSpooler.setFont(font)
        self.qTaskType = QtGui.QComboBox(qSpooler)
        self.qTaskType.setGeometry(QtCore.QRect(531, 10, 170, 31))
        self.qTaskType.setEditable(False)
        self.qTaskType.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.qTaskType.setObjectName("qTaskType")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.qTaskType.addItem("")
        self.label = QtGui.QLabel(qSpooler)
        self.label.setGeometry(QtCore.QRect(448, 14, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.alfredBtn = QtGui.QPushButton(qSpooler)
        self.alfredBtn.setEnabled(True)
        self.alfredBtn.setGeometry(QtCore.QRect(520, 583, 180, 31))
        self.alfredBtn.setObjectName("alfredBtn")
        self.tractorBtn = QtGui.QPushButton(qSpooler)
        self.tractorBtn.setGeometry(QtCore.QRect(520, 578, 180, 41))
        self.tractorBtn.setObjectName("tractorBtn")
        self.qBtn = QtGui.QPushButton(qSpooler)
        self.qBtn.setGeometry(QtCore.QRect(10, 10, 111, 27))
        self.qBtn.setObjectName("qBtn")
        self.browseSeqBtn = QtGui.QPushButton(qSpooler)
        self.browseSeqBtn.setGeometry(QtCore.QRect(475, 264, 31, 31))
        self.browseSeqBtn.setObjectName("browseSeqBtn")
        self.label_2 = QtGui.QLabel(qSpooler)
        self.label_2.setGeometry(QtCore.QRect(11, 244, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.seqTo = QtGui.QSpinBox(qSpooler)
        self.seqTo.setGeometry(QtCore.QRect(638, 284, 64, 31))
        self.seqTo.setMaximum(9999999)
        self.seqTo.setObjectName("seqTo")
        self.seqFrom = QtGui.QSpinBox(qSpooler)
        self.seqFrom.setGeometry(QtCore.QRect(638, 246, 64, 31))
        self.seqFrom.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.seqFrom.setMaximum(9999999)
        self.seqFrom.setSingleStep(1)
        self.seqFrom.setObjectName("seqFrom")
        self.label_3 = QtGui.QLabel(qSpooler)
        self.label_3.setGeometry(QtCore.QRect(530, 253, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(qSpooler)
        self.label_4.setGeometry(QtCore.QRect(531, 290, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.browseScriptBtn = QtGui.QPushButton(qSpooler)
        self.browseScriptBtn.setGeometry(QtCore.QRect(670, 433, 31, 31))
        self.browseScriptBtn.setObjectName("browseScriptBtn")
        self.label_5 = QtGui.QLabel(qSpooler)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(10, 307, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(qSpooler)
        self.label_6.setGeometry(QtCore.QRect(340, 410, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.genTaskBtn = QtGui.QPushButton(qSpooler)
        self.genTaskBtn.setGeometry(QtCore.QRect(340, 477, 101, 31))
        self.genTaskBtn.setObjectName("genTaskBtn")
        self.label_8 = QtGui.QLabel(qSpooler)
        self.label_8.setGeometry(QtCore.QRect(95, 18, 381, 61))
        font = QtGui.QFont()
        font.setFamily("DejaVu LGC Sans")
        font.setPointSize(24)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtGui.QLabel(qSpooler)
        self.label_10.setGeometry(QtCore.QRect(179, 49, 211, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(7)
        font.setWeight(75)
        font.setItalic(True)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(qSpooler)
        self.label_11.setGeometry(QtCore.QRect(177, 60, 211, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(7)
        font.setWeight(75)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.qTaskSeq = QtGui.QLineEdit(qSpooler)
        self.qTaskSeq.setGeometry(QtCore.QRect(10, 264, 467, 32))
        self.qTaskSeq.setObjectName("qTaskSeq")
        self.qScriptPath = QtGui.QLineEdit(qSpooler)
        self.qScriptPath.setGeometry(QtCore.QRect(340, 433, 331, 33))
        self.qScriptPath.setObjectName("qScriptPath")
        self.frame = QtGui.QFrame(qSpooler)
        self.frame.setGeometry(QtCore.QRect(4, 93, 511, 137))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(3)
        self.frame.setObjectName("frame")
        self.prjPathBtn = QtGui.QPushButton(self.frame)
        self.prjPathBtn.setGeometry(QtCore.QRect(464, 92, 38, 39))
        self.prjPathBtn.setObjectName("prjPathBtn")
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(5, 73, 490, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.taskTitle = QtGui.QLineEdit(self.frame)
        self.taskTitle.setGeometry(QtCore.QRect(4, 25, 499, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.taskTitle.setFont(font)
        self.taskTitle.setObjectName("taskTitle")
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(5, 6, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.qPrjPath = QtGui.QLineEdit(self.frame)
        self.qPrjPath.setGeometry(QtCore.QRect(4, 92, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.qPrjPath.setFont(font)
        self.qPrjPath.setObjectName("qPrjPath")
        self.autoStart = QtGui.QCheckBox(qSpooler)
        self.autoStart.setGeometry(QtCore.QRect(570, 251, 61, 22))
        self.autoStart.setChecked(True)
        self.autoStart.setObjectName("autoStart")
        self.autoEnd = QtGui.QCheckBox(qSpooler)
        self.autoEnd.setGeometry(QtCore.QRect(570, 288, 61, 22))
        self.autoEnd.setChecked(True)
        self.autoEnd.setObjectName("autoEnd")
        self.renderBtn = QtGui.QPushButton(qSpooler)
        self.renderBtn.setGeometry(QtCore.QRect(531, 203, 170, 27))
        self.renderBtn.setObjectName("renderBtn")
        self.renCpBtn = QtGui.QPushButton(qSpooler)
        self.renCpBtn.setGeometry(QtCore.QRect(531, 166, 170, 27))
        self.renCpBtn.setObjectName("renCpBtn")
        self.renMvBtn = QtGui.QPushButton(qSpooler)
        self.renMvBtn.setGeometry(QtCore.QRect(531, 129, 170, 27))
        self.renMvBtn.setObjectName("renMvBtn")
        self.patchBtn = QtGui.QPushButton(qSpooler)
        self.patchBtn.setGeometry(QtCore.QRect(531, 93, 170, 27))
        self.patchBtn.setObjectName("patchBtn")
        self.label_12 = QtGui.QLabel(qSpooler)
        self.label_12.setGeometry(QtCore.QRect(465, 56, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.frame_2 = QtGui.QFrame(qSpooler)
        self.frame_2.setGeometry(QtCore.QRect(10, 432, 320, 76))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_19 = QtGui.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(227, 48, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.atleastSpin = QtGui.QSpinBox(self.frame_2)
        self.atleastSpin.setGeometry(QtCore.QRect(130, 16, 64, 31))
        self.atleastSpin.setMinimum(1)
        self.atleastSpin.setMaximum(9999999)
        self.atleastSpin.setProperty("value", 1)
        self.atleastSpin.setObjectName("atleastSpin")
        self.atmostSpin = QtGui.QSpinBox(self.frame_2)
        self.atmostSpin.setGeometry(QtCore.QRect(14, 16, 64, 31))
        self.atmostSpin.setMinimum(1)
        self.atmostSpin.setMaximum(9999999)
        self.atmostSpin.setProperty("value", 1)
        self.atmostSpin.setObjectName("atmostSpin")
        self.samehostSpin = QtGui.QSpinBox(self.frame_2)
        self.samehostSpin.setGeometry(QtCore.QRect(240, 16, 64, 31))
        self.samehostSpin.setMinimum(1)
        self.samehostSpin.setMaximum(9999999)
        self.samehostSpin.setProperty("value", 1)
        self.samehostSpin.setObjectName("samehostSpin")
        self.label_18 = QtGui.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(126, 48, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_17 = QtGui.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(9, 48, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_16 = QtGui.QLabel(qSpooler)
        self.label_16.setGeometry(QtCore.QRect(11, 408, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.frame_3 = QtGui.QFrame(qSpooler)
        self.frame_3.setGeometry(QtCore.QRect(10, 544, 320, 76))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.periorityTxt = QtGui.QSpinBox(self.frame_3)
        self.periorityTxt.setGeometry(QtCore.QRect(240, 12, 64, 31))
        self.periorityTxt.setMinimum(0)
        self.periorityTxt.setMaximum(9999999)
        self.periorityTxt.setProperty("value", 50)
        self.periorityTxt.setObjectName("periorityTxt")
        self.perTask = QtGui.QSpinBox(self.frame_3)
        self.perTask.setGeometry(QtCore.QRect(17, 12, 64, 31))
        self.perTask.setMinimum(1)
        self.perTask.setMaximum(9999999)
        self.perTask.setObjectName("perTask")
        self.label_13 = QtGui.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(0, 48, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.skipSpin = QtGui.QSpinBox(self.frame_3)
        self.skipSpin.setGeometry(QtCore.QRect(130, 12, 64, 31))
        self.skipSpin.setMinimum(0)
        self.skipSpin.setMaximum(9999999)
        self.skipSpin.setProperty("value", 0)
        self.skipSpin.setObjectName("skipSpin")
        self.label_14 = QtGui.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(225, 48, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(110, 48, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_20 = QtGui.QLabel(qSpooler)
        self.label_20.setGeometry(QtCore.QRect(10, 520, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.optionalArgs = QtGui.QPlainTextEdit(qSpooler)
        self.optionalArgs.setGeometry(QtCore.QRect(10, 330, 692, 69))
        self.optionalArgs.setObjectName("optionalArgs")
        self.profilesBox = QtGui.QComboBox(qSpooler)
        self.profilesBox.setGeometry(QtCore.QRect(520, 477, 181, 31))
        self.profilesBox.setEditable(False)
        self.profilesBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.profilesBox.setObjectName("profilesBox")
        self.profilesBox.addItem("")
        self.profilesBox.addItem("")
        self.profilesBox.addItem("")
        self.profilesBox.addItem("")
        self.profilesBox.addItem("")
        self.profilesBox.addItem("")
        self.profilesBox.addItem("")
        self.label_21 = QtGui.QLabel(qSpooler)
        self.label_21.setGeometry(QtCore.QRect(340, 520, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.frame_4 = QtGui.QFrame(qSpooler)
        self.frame_4.setGeometry(QtCore.QRect(340, 544, 131, 76))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.perTask_2 = QtGui.QSpinBox(self.frame_4)
        self.perTask_2.setGeometry(QtCore.QRect(35, 12, 64, 31))
        self.perTask_2.setMinimum(1)
        self.perTask_2.setMaximum(9999999)
        self.perTask_2.setObjectName("perTask_2")
        self.label_22 = QtGui.QLabel(self.frame_4)
        self.label_22.setGeometry(QtCore.QRect(11, 48, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.curLayerBtn = QtGui.QPushButton(qSpooler)
        self.curLayerBtn.setEnabled(False)
        self.curLayerBtn.setGeometry(QtCore.QRect(520, 510, 180, 29))
        self.curLayerBtn.setObjectName("curLayerBtn")
        self.engineTxt = QtGui.QComboBox(qSpooler)
        self.engineTxt.setGeometry(QtCore.QRect(530, 52, 171, 29))
        self.engineTxt.setEditable(True)
        self.engineTxt.setObjectName("engineTxt")
        self.checkBox = QtGui.QCheckBox(qSpooler)
        self.checkBox.setGeometry(QtCore.QRect(520, 550, 91, 23))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtGui.QCheckBox(qSpooler)
        self.checkBox_2.setGeometry(QtCore.QRect(620, 550, 111, 23))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")

        self.retranslateUi(qSpooler)
        QtCore.QObject.connect(self.qBtn, QtCore.SIGNAL("clicked()"), qSpooler.close)
        QtCore.QMetaObject.connectSlotsByName(qSpooler)
        qSpooler.setTabOrder(self.qTaskType, self.seqFrom)
        qSpooler.setTabOrder(self.seqFrom, self.seqTo)
        qSpooler.setTabOrder(self.seqTo, self.taskTitle)
        qSpooler.setTabOrder(self.taskTitle, self.qPrjPath)
        qSpooler.setTabOrder(self.qPrjPath, self.qTaskSeq)
        qSpooler.setTabOrder(self.qTaskSeq, self.qScriptPath)
        qSpooler.setTabOrder(self.qScriptPath, self.autoStart)
        qSpooler.setTabOrder(self.autoStart, self.autoEnd)
        qSpooler.setTabOrder(self.autoEnd, self.patchBtn)
        qSpooler.setTabOrder(self.patchBtn, self.renMvBtn)
        qSpooler.setTabOrder(self.renMvBtn, self.renCpBtn)
        qSpooler.setTabOrder(self.renCpBtn, self.renderBtn)
        qSpooler.setTabOrder(self.renderBtn, self.prjPathBtn)
        qSpooler.setTabOrder(self.prjPathBtn, self.browseSeqBtn)
        qSpooler.setTabOrder(self.browseSeqBtn, self.browseScriptBtn)
        qSpooler.setTabOrder(self.browseScriptBtn, self.genTaskBtn)
        qSpooler.setTabOrder(self.genTaskBtn, self.alfredBtn)
        qSpooler.setTabOrder(self.alfredBtn, self.tractorBtn)
        qSpooler.setTabOrder(self.tractorBtn, self.qBtn)

    def retranslateUi(self, qSpooler):
        qSpooler.setWindowTitle(QtGui.QApplication.translate("qSpooler", "Alfred/Tractor Job Spooler", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(0, QtGui.QApplication.translate("qSpooler", "Arnold Render", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(1, QtGui.QApplication.translate("qSpooler", "Renderman Render", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(2, QtGui.QApplication.translate("qSpooler", "Massive Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(3, QtGui.QApplication.translate("qSpooler", "Katana Batch", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(4, QtGui.QApplication.translate("qSpooler", "Nuke Render", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(5, QtGui.QApplication.translate("qSpooler", "Maya Batch", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(6, QtGui.QApplication.translate("qSpooler", "Maya Script", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(7, QtGui.QApplication.translate("qSpooler", "Mentalray Render", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(8, QtGui.QApplication.translate("qSpooler", "FumeFX Sim", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(9, QtGui.QApplication.translate("qSpooler", "FumeFX Render", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(10, QtGui.QApplication.translate("qSpooler", "Renderman .rib gen", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(11, QtGui.QApplication.translate("qSpooler", "Arnold .ass gen", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(12, QtGui.QApplication.translate("qSpooler", "Mentalray .mi gen", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(13, QtGui.QApplication.translate("qSpooler", "Fusion Render", None, QtGui.QApplication.UnicodeUTF8))
        self.qTaskType.setItemText(14, QtGui.QApplication.translate("qSpooler", "Shake Render", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("qSpooler", "Task Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.alfredBtn.setText(QtGui.QApplication.translate("qSpooler", "Send to Alfred", None, QtGui.QApplication.UnicodeUTF8))
        self.tractorBtn.setText(QtGui.QApplication.translate("qSpooler", "Launch", None, QtGui.QApplication.UnicodeUTF8))
        self.qBtn.setText(QtGui.QApplication.translate("qSpooler", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.browseSeqBtn.setText(QtGui.QApplication.translate("qSpooler", "....", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("qSpooler", "Task Related File(s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("qSpooler", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("qSpooler", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.browseScriptBtn.setText(QtGui.QApplication.translate("qSpooler", "....", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("qSpooler", "Optional Task Arguments:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("qSpooler", "Task script filename (Optional):", None, QtGui.QApplication.UnicodeUTF8))
        self.genTaskBtn.setText(QtGui.QApplication.translate("qSpooler", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("qSpooler", "Job Spooler", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("qSpooler", "w w w . n o t h i n g - r e a l . c o m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("qSpooler", "v i s u a l   E f f e c t s   H o u s e", None, QtGui.QApplication.UnicodeUTF8))
        self.prjPathBtn.setText(QtGui.QApplication.translate("qSpooler", "//", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("qSpooler", "Project Workspace (Net path for Render Farms):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("qSpooler", "Job Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.autoStart.setText(QtGui.QApplication.translate("qSpooler", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.autoEnd.setText(QtGui.QApplication.translate("qSpooler", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.renderBtn.setText(QtGui.QApplication.translate("qSpooler", "Render Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.renCpBtn.setText(QtGui.QApplication.translate("qSpooler", "Rename/Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.renMvBtn.setText(QtGui.QApplication.translate("qSpooler", "Rename/Move", None, QtGui.QApplication.UnicodeUTF8))
        self.patchBtn.setText(QtGui.QApplication.translate("qSpooler", "Patch ASS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("qSpooler", "Engine:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("qSpooler", "samehost", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("qSpooler", "atleast", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("qSpooler", "atmost", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("qSpooler", "Slots Control:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("qSpooler", "Task Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("qSpooler", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("qSpooler", "Skip", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("qSpooler", "Task Control:", None, QtGui.QApplication.UnicodeUTF8))
        self.profilesBox.setItemText(0, QtGui.QApplication.translate("qSpooler", "Local Renderfarm", None, QtGui.QApplication.UnicodeUTF8))
        self.profilesBox.setItemText(1, QtGui.QApplication.translate("qSpooler", "Local HighMem", None, QtGui.QApplication.UnicodeUTF8))
        self.profilesBox.setItemText(2, QtGui.QApplication.translate("qSpooler", "Local Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.profilesBox.setItemText(3, QtGui.QApplication.translate("qSpooler", "Vendor Renderfarm", None, QtGui.QApplication.UnicodeUTF8))
        self.profilesBox.setItemText(4, QtGui.QApplication.translate("qSpooler", "Vendor HighMem", None, QtGui.QApplication.UnicodeUTF8))
        self.profilesBox.setItemText(5, QtGui.QApplication.translate("qSpooler", "FumeFX Sim/Ren", None, QtGui.QApplication.UnicodeUTF8))
        self.profilesBox.setItemText(6, QtGui.QApplication.translate("qSpooler", "Nuke blades", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("qSpooler", "Every:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("qSpooler", "Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.curLayerBtn.setText(QtGui.QApplication.translate("qSpooler", "Only Current Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("qSpooler", "sync", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("qSpooler", "render", None, QtGui.QApplication.UnicodeUTF8))

