# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qRename_Win.ui'
#
# Created: Wed Aug  8 22:14:31 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RenameWinUI(object):
    def setupUi(self, RenameWinUI):
        RenameWinUI.setObjectName(_fromUtf8("RenameWinUI"))
        RenameWinUI.resize(506, 376)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        RenameWinUI.setFont(font)
        self.qOrigSeqDir = QtGui.QLineEdit(RenameWinUI)
        self.qOrigSeqDir.setGeometry(QtCore.QRect(20, 97, 437, 32))
        self.qOrigSeqDir.setObjectName(_fromUtf8("qOrigSeqDir"))
        self.browseNewSeqBtn = QtGui.QPushButton(RenameWinUI)
        self.browseNewSeqBtn.setGeometry(QtCore.QRect(456, 97, 31, 31))
        self.browseNewSeqBtn.setObjectName(_fromUtf8("browseNewSeqBtn"))
        self.browseDistSeqBtn = QtGui.QPushButton(RenameWinUI)
        self.browseDistSeqBtn.setGeometry(QtCore.QRect(456, 190, 31, 31))
        self.browseDistSeqBtn.setObjectName(_fromUtf8("browseDistSeqBtn"))
        self.qSeqDist = QtGui.QLineEdit(RenameWinUI)
        self.qSeqDist.setGeometry(QtCore.QRect(20, 223, 467, 32))
        self.qSeqDist.setObjectName(_fromUtf8("qSeqDist"))
        self.renCpBtn = QtGui.QPushButton(RenameWinUI)
        self.renCpBtn.setGeometry(QtCore.QRect(20, 330, 161, 27))
        self.renCpBtn.setObjectName(_fromUtf8("renCpBtn"))
        self.renMvBtn = QtGui.QPushButton(RenameWinUI)
        self.renMvBtn.setGeometry(QtCore.QRect(185, 330, 161, 27))
        self.renMvBtn.setObjectName(_fromUtf8("renMvBtn"))
        self.colseBtn = QtGui.QPushButton(RenameWinUI)
        self.colseBtn.setGeometry(QtCore.QRect(374, 330, 111, 27))
        self.colseBtn.setObjectName(_fromUtf8("colseBtn"))
        self.label = QtGui.QLabel(RenameWinUI)
        self.label.setGeometry(QtCore.QRect(23, 77, 61, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(RenameWinUI)
        self.label_2.setGeometry(QtCore.QRect(23, 170, 41, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.qSeqOrig = QtGui.QLineEdit(RenameWinUI)
        self.qSeqOrig.setGeometry(QtCore.QRect(20, 130, 467, 32))
        self.qSeqOrig.setObjectName(_fromUtf8("qSeqOrig"))
        self.qDistSeqDir = QtGui.QLineEdit(RenameWinUI)
        self.qDistSeqDir.setGeometry(QtCore.QRect(20, 190, 437, 32))
        self.qDistSeqDir.setObjectName(_fromUtf8("qDistSeqDir"))
        self.qTimeRange = QtGui.QLineEdit(RenameWinUI)
        self.qTimeRange.setEnabled(True)
        self.qTimeRange.setGeometry(QtCore.QRect(137, 270, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.qTimeRange.setFont(font)
        self.qTimeRange.setText(_fromUtf8(""))
        self.qTimeRange.setAlignment(QtCore.Qt.AlignCenter)
        self.qTimeRange.setReadOnly(True)
        self.qTimeRange.setObjectName(_fromUtf8("qTimeRange"))
        self.label_10 = QtGui.QLabel(RenameWinUI)
        self.label_10.setGeometry(QtCore.QRect(154, 33, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_8 = QtGui.QLabel(RenameWinUI)
        self.label_8.setGeometry(QtCore.QRect(70, 3, 381, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu LGC Sans"))
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_11 = QtGui.QLabel(RenameWinUI)
        self.label_11.setGeometry(QtCore.QRect(152, 43, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))

        self.retranslateUi(RenameWinUI)
        QtCore.QObject.connect(self.colseBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), RenameWinUI.close)
        QtCore.QMetaObject.connectSlotsByName(RenameWinUI)
        RenameWinUI.setTabOrder(self.qOrigSeqDir, self.qSeqOrig)
        RenameWinUI.setTabOrder(self.qSeqOrig, self.qDistSeqDir)
        RenameWinUI.setTabOrder(self.qDistSeqDir, self.qSeqDist)
        RenameWinUI.setTabOrder(self.qSeqDist, self.browseNewSeqBtn)
        RenameWinUI.setTabOrder(self.browseNewSeqBtn, self.browseDistSeqBtn)
        RenameWinUI.setTabOrder(self.browseDistSeqBtn, self.renMvBtn)
        RenameWinUI.setTabOrder(self.renMvBtn, self.renCpBtn)
        RenameWinUI.setTabOrder(self.renCpBtn, self.colseBtn)

    def retranslateUi(self, RenameWinUI):
        RenameWinUI.setWindowTitle(QtGui.QApplication.translate("RenameWinUI", "Rename/Move - Rename/Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.browseNewSeqBtn.setText(QtGui.QApplication.translate("RenameWinUI", "....", None, QtGui.QApplication.UnicodeUTF8))
        self.browseDistSeqBtn.setText(QtGui.QApplication.translate("RenameWinUI", "....", None, QtGui.QApplication.UnicodeUTF8))
        self.renCpBtn.setText(QtGui.QApplication.translate("RenameWinUI", "Rename/Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.renMvBtn.setText(QtGui.QApplication.translate("RenameWinUI", "Rename/Move", None, QtGui.QApplication.UnicodeUTF8))
        self.colseBtn.setText(QtGui.QApplication.translate("RenameWinUI", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RenameWinUI", "From:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RenameWinUI", "To:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("RenameWinUI", "w w w . n o t h i n g - r e a l . c o m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("RenameWinUI", "Job Spooler", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("RenameWinUI", "v i s u a l   E f f e c t s   H o u s e", None, QtGui.QApplication.UnicodeUTF8))

